# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

_defaults: &defaults
  working_directory: ~/repo
  steps:
    - checkout
    - run:
        name: dependencies
        command: |
          sudo apt-get install pdftk
          sudo pip install pytest
    - run:
        name: run tests
        command: |
          mkdir test-reports
          pytest --junitxml=test-reports/junit.xml test.py

jobs:
  python2:
    docker:
      - image: circleci/python:2.7
    <<: *defaults

  python3:
    docker:
      - image: circleci/python:3.6
    <<: *defaults

workflows:
  version: 2
  tests:
    jobs:
      - python2
      - python3